import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/components/nav/nav'

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-br from-bg-purple-light via-bg-purple-mid to-bg-purple-dark'>
        <Nav></Nav>
        {children}
      </body>
    </html>
  )
}
